name: hearatale_literacy_app
description: Hearatale literacy app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.15.1
  http: ^0.13.1
  intl: ^0.17.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/dropbox/Cropped/
    - assets/dropbox/Cropped/Icon_7.1.png
    - assets/dropbox/Cropped/Icon_7.2.png
    - assets/dropbox/Cropped/Icon_7.3.png
    - assets/dropbox/sectionOne/OnePointOne/
    - assets/fix_fixed_fixing.mp3
    - assets/help_helped_helping.mp3
    - assets/jump_jumped_jumping.mp3
    - assets/own_owned_owning.mp3
    - assets/paint_painted_painting.mp3
    - assets/drop_dropped_dropping.mp3
    - assets/fib_fibbed_fibbing.mp3
    - assets/nap_napped_napping.mp3
    - assets/skip_skipped_skipping.mp3
    - assets/stop_stopped_stopping.mp3
    - assets/bake_baked_baking.mp3
    - assets/dance_danced_dancing.mp3
    - assets/move_moved_moving.mp3
    - assets/tickle_tickled_tickling.mp3
    - assets/tumble_tumbled_tumbling.mp3
    - assets/carry_carried_carrying.mp3
    - assets/cry_cried_crying.mp3
    - assets/dirty_dirtied_dirtying.mp3
    - assets/empty_emptied_emptying.mp3
    - assets/fry_fried_frying.mp3
    - assets/try_tried_trying.mp3
    - assets/help_helps.mp3
    - assets/jump_jumps.mp3
    - assets/kick_kicks.mp3
    - assets/sing_sings.mp3
    - assets/bully_bullies.mp3
    - assets/carry_carries.mp3
    - assets/cry_cries.mp3
    - assets/dirty_dirties.mp3
    - assets/fly_flies.mp3
    - assets/spy_spies.mp3
    - assets/try_tries.mp3
    - assets/hitch_hitches.mp3
    - assets/scratch_scratches.mp3
    - assets/teach_teaches.mp3
    - assets/touch_touches.mp3
    - assets/watch_watches.mp3
    - assets/guess_guesses.mp3
    - assets/hiss_hisses.mp3
    - assets/kiss_kisses.mp3
    - assets/miss_misses.mp3
    - assets/pass_passes.mp3
    - assets/toss_tosses.mp3
    - assets/crash_crashes.mp3
    - assets/fish_fishes.mp3
    - assets/push_pushes.mp3
    - assets/vanish_vanishes.mp3
    - assets/wash_washes.mp3
    - assets/wish_wishes.mp3
    - assets/box_boxes.mp3
    - assets/fix_fixes.mp3
    - assets/mix_mixes.mp3
    - assets/relax_relaxes.mp3
    - assets/wax_waxes.mp3
    - assets/dark.mp3
    - assets/hard.mp3
    - assets/long.mp3
    - assets/quiet.mp3
    - assets/small.mp3
    - assets/strong.mp3
    - assets/sweet.mp3
    - assets/young.mp3
    - assets/blue.mp3
    - assets/large.mp3
    - assets/little.mp3
    - assets/nice.mp3
    - assets/rude.mp3
    - assets/strange.mp3
    - assets/tame.mp3
    - assets/wide.mp3
    - assets/cranky.mp3
    - assets/friendly.mp3
    - assets/happy.mp3
    - assets/icy.mp3
    - assets/pretty.mp3
    - assets/silly.mp3
    - assets/sneaky.mp3
    - assets/sorry.mp3
    - assets/big.mp3
    - assets/fat.mp3
    - assets/flat.mp3
    - assets/hot.mp3
    - assets/red.mp3
    - assets/sad.mp3
    - assets/thin.mp3
    - assets/wet.mp3
    - assets/sleep_sleeps.mp3
    - assets/talk_talks.mp3
    - assets/think_thinks.mp3
    - assets/work_works.mp3
    - assets/boot's_theboot'sbootstring.mp3
    - assets/child's_thechild'sbook.mp3
    - assets/dog's_thedog'scollar.mp3
    - assets/dress's_thedress'scollar.mp3
    - assets/elf's_theelf'slantern.mp3
    - assets/firefly's_thefirefly'shead.mp3
    - assets/flower's_theflower'sstem.mp3
    - assets/foot's_thefoot'stoenails.mp3
    - assets/fox's_thefox'stail.mp3
    - assets/goose's_thegoose'sfeet.mp3
    - assets/man's_theman'ssaw.mp3
    - assets/mouse's_themouse'snose.mp3
    - assets/peach's_thepeach'sseed.mp3
    - assets/person's_theperson'sguitar.mp3
    - assets/tooth's_thetooth'spoint.mp3
    - assets/woman's_thewoman'sheadband.mp3
    - assets/worker's_theworker'shardhat.mp3
    - assets/boots'_theboots'tongues.mp3
    - assets/dogs'_thedogs'leashes.mp3
    - assets/dresses'_thedresses'_sleeves.mp3
    - assets/elves'_theelves'caps.mp3
    - assets/fireflies'_thefireflies'tails.mp3
    - assets/flowers'_theflowers'leaves.mp3
    - assets/foxes'_thefoxes'noses.mp3
    - assets/peaches'_thepeaches'stems.mp3
    - assets/workers'_theworkers'_tools.mp3
    - assets/children's_thechildren'steacher.mp3
    - assets/feet's_thefeet'sbigtoes.mp3
    - assets/geese's_thegesse'sbeaks.mp3
    - assets/men's_themen'shands.mp3
    - assets/mice's_themice'stails.mp3
    - assets/people's_thepeople'shands.mp3
    - assets/teeth's_theteeth'scolor.mp3
    - assets/women's_thewomen'sfaces.mp3
    - assets/bubble_bubbles.mp3
    - assets/cookie_cookies.mp3
    - assets/creature_creatures.mp3
    - assets/frog_frogs.mp3
    - assets/giraffe_giraffes.mp3
    - assets/puddle_puddles.mp3
    - assets/stripe_stripes.mp3
    - assets/vehicle_vehicles.mp3
    - assets/bus_busses.mp3
    - assets/dress_dresses.mp3
    - assets/glass_glasses.mp3
    - assets/guess_guesses.mp3
    - assets/kiss_kisses.mp3
    - assets/walrus_walruses.mp3
    - assets/scratch_scratches.mp3
    - assets/watch_watches.mp3
    - assets/box_boxes.mp3
    - assets/mix_mixes.mp3
    - assets/wax_waxes.mp3
    - assets/fly_flies.mp3
    - assets/spy_spies.mp3
    - assets/aircraft.mp3
    - assets/bison.mp3
    - assets/deer.mp3
    - assets/elk.mp3
    - assets/fish.mp3
    - assets/jellyfish.mp3
    - assets/moose.mp3
    - assets/reindeer.mp3
    - assets/sheep.mp3
    - assets/spacecraft.mp3
    - assets/watercraft.mp3
    - assets/dropbox/sectionOne/OnePointTwo/
    - assets/dropbox/sectionOne/OnePointThree/
    - assets/dropbox/sectionOne/OnePointFour/
    - assets/dropbox/sectionTwo/TwoPointOne/
    - assets/dropbox/sectionTwo/TwoPointTwo/
    - assets/dropbox/sectionTwo/TwoPointThree/
    - assets/dropbox/sectionTwo/TwoPointFour/
    - assets/dropbox/sectionTwo/TwoPointFive/
    - assets/dropbox/sectionTwo/TwoPointSix/
    - assets/dropbox/sectionThree/ThreePointOne/
    - assets/dropbox/sectionThree/ThreePointTwo/
    - assets/dropbox/sectionThree/ThreePointThree/
    - assets/dropbox/sectionThree/ThreePointFour/
    - assets/dropbox/sectionFour/FourPointOne/
    - assets/dropbox/sectionFour/FourPointTwo/
    - assets/dropbox/sectionFour/FourPointThree/
    - assets/dropbox/sectionFour/FourPointFour/
    - assets/dropbox/sectionFour/FourPointFive/
    - assets/dropbox/sectionFour/FourPointSix/
    - assets/dropbox/sectionFour/FourPointSeven/
    - assets/dropbox/sectionFour/FourPointEight/
    - assets/dropbox/sectionFour/FourPointNine/
    - assets/dropbox/sectionFour/FourPointTen/
    - assets/dropbox/sectionFive/FivePointOne/
    - assets/dropbox/sectionFive/FivePointTwo/
    - assets/dropbox/sectionFive/FivePointThree/
    - assets/dropbox/SectionSix/SixPointOne/
    - assets/dropbox/SectionSix/SixPointTwo/
    - assets/dropbox/SectionSix/SixPointThree/
    - assets/dropbox/SectionSix/SixPointFour/
    - assets/dropbox/SectionSix/SixPointFive/
    - assets/dropbox/SectionSix/SixPointSix/
    - assets/dropbox/SectionSix/SixPointSeven/
    - assets/dropbox/SectionSix/SixPointEight/
    - assets/dropbox/sectionSeven/
    - assets/dropbox/SectionEight/EightPointOne/
    - assets/dropbox/SectionEight/EightPointTwo/
    - assets/dropbox/SectionEight/EightPointThree/
    - assets/dropbox/SectionEight/EightPointFour/
    - assets/dropbox/SectionEight/EightPointFive/
    - assets/dropbox/SectionEight/EightPointSix/
    - assets/dropbox/SectionEight/EightPointSeven/
    - assets/dropbox/SectionEight/EightPointEight/
    - assets/dropbox/SectionEight/EightPointNine/
    - assets/dropbox/SectionNine/NinePointZero/
    - assets/dropbox/SectionNine/NinePointOne/
    - assets/dropbox/SectionNine/NinePointTwo/
    - assets/dropbox/SectionNine/NinePointThree/
    - assets/dropbox/SectionNine/NinePointFour/
    - assets/dropbox/SectionNine/NinePointFive/
    - assets/dropbox/SectionNine/NinePointSix/
    - assets/dropbox/SectionNine/NinePointSeven/
    - assets/dropbox/SectionTen/
    - assets/dropbox/wordStructuresMenu/
    - assets/stars/
    - assets/rewards/
  fonts:
    - family: Comic
      fonts:
        - asset: assets/comic-sans-ms/COMIC.TTF

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
